spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
  application:
    name: intershop-shop-service
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  cache:
    redis:
      time-to-live: 60000

payment:
  api:
    url: ${PAYMENT_API_URL}
