services:
  postgres:
    image: postgres:latest
    container_name: postgres-r2dbc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  shop-service:
    build:
      context: ./shop-service
    container_name: intershop-shop-service
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  payment-service:
    build:
      context: ./payment-service
    container_name: intershop-payment-service
    ports:
      - "8081:8080"
    depends_on:
      - shop-service
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge