spring:
  web:
    resources:
      encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
    cache: false
  application:
    name: intershop-reac
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
