spring:
  web:
    resources:
      encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
    cache: false
  application:
    name: intershop-reac
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver

server:
  servlet:
    session:
      cookie:
        name: SESSION
        secure: false
        same-site: Lax

